import type { Project, Experience, SkillCategory } from '@/types'

export const projects: Project[] = [
  // 2023 - Presente (Mais Recentes)
  {
    id: 'enor-securities',
    title: 'APP Bank - Crypto Wallet',
    company: 'Enor Securities',
    description:
      'Construí e mantive a carteira cripto nacional baseada em El Salvador, focada em onboarding seguro, operações de carteira, validação de identidade, e fluxos multilíngues para usuários internacionais. Mantenho e evoluo toda a arquitetura v2 com foco em segurança, confiabilidade e internacionalização. Lidei arquitetura v2 com autenticação mais forte, hardening de API, obfuscação, e revisões estáticas baseadas em JADX. Entreguei fluxos multilíngues (ES/PT/EN), estabilizei UX transacional, fortaleci pipelines GitLab CI, e melhorei documentação e processos de engenharia em toda a equipe.',
    technologies: [
      'React Native',
      'TypeScript',
      'Security',
      'Obfuscation',
      'JADX',
      'GitLab CI',
      'Multi-language',
      'Identity Validation',
    ],
    domain: 'Fintech',
    period: '2023 - Presente',
    highlights: [
      'Carteira cripto nacional (El Salvador)',
      'Arquitetura v2 com segurança reforçada',
      'Fluxos multilíngues (ES/PT/EN)',
      'Revisões estáticas de segurança',
      'Melhorias em processos de engenharia',
    ],
    iosUrl: 'https://apps.apple.com/br/app/enor-securities/id6475595155',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.enorsecurities.mobile.app&hl=pt_BR',
  },
  {
    id: 'gympass-wellhub',
    title: 'Gympass / Wellhub',
    company: 'Invillia',
    description:
      'Transformei um app multiregional usado por mais de 20 milhões de usuários em um produto totalmente alinhado com WCAG 2.1. Minha atuação focou em engenharia de acessibilidade cross-platform, onde construí componentes a11y-first para o Yoga Design System (open-source) e Yoga Inner, resolvendo inconsistências profundas entre TalkBack e VoiceOver que impactavam a experiência de usuários com deficiência visual em 11 países. Implementei correções estruturais na navegação semântica, gerenciamento de foco, anúncios dinâmicos de conteúdo e validação de árvore de leitores de tela. Fortaleci a cultura de desenvolvimento através de orientação arquitetural, padrões reutilizáveis e validação a11y automatizada em pipelines CI/CD, garantindo que todas as novas features sigam padrões de acessibilidade desde o início. Conduzi workshops técnicos para equipes de desenvolvimento, design e produto, estabelecendo práticas de acessibilidade como parte fundamental do processo de desenvolvimento.',
    technologies: [
      'React Native',
      'TypeScript',
      'WCAG 2.1',
      'TalkBack',
      'VoiceOver',
      'Yoga Design System',
      'Semantic Navigation',
      'Focus Management',
      'CI/CD',
      'Accessibility Testing',
    ],
    domain: 'Health & Wellness',
    period: '2023 - Maio 2025',
    highlights: [
      'App usado por 20M+ usuários em 11 países',
      'Componentes a11y-first para design system open-source (Yoga DS)',
      'Workshops e cultura de acessibilidade organizacional',
      'Validação a11y automatizada em CI/CD',
      'Resolução de inconsistências TalkBack/VoiceOver',
      'Navegação semântica e gerenciamento de foco implementados',
    ],
    iosUrl: 'https://apps.apple.com/br/app/wellhub-gympass/id703761434',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.gympass&hl=pt_BR',
    webUrl: 'https://gympass.github.io/yoga/',
  },
  // Sites 2023
  {
    id: 'guato-digital',
    title: 'Guato Digital',
    company: 'Freelance',
    description:
      'Website desenvolvido para empresa de soluções digitais, com design moderno e responsivo. Implementação de interface otimizada para conversão e experiência do usuário.',
    technologies: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    domain: 'Web Development',
    period: '2023',
    highlights: [
      'Design moderno e responsivo',
      'Otimizado para conversão',
      'Performance otimizada',
    ],
    webUrl: 'https://www.guatodigital.com/',
  },
  {
    id: 'pamela-decoracao',
    title: 'Pamela Decoração',
    company: 'Freelance',
    description:
      'Website para empresa de decoração e design de interiores, com galeria de projetos, portfólio visual e sistema de contato. Interface elegante e intuitiva.',
    technologies: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    domain: 'Web Development',
    period: '2023',
    highlights: [
      'Galeria de projetos',
      'Portfólio visual',
      'Design elegante',
    ],
    webUrl: 'https://www.pameladecoracao.com.br/',
  },
  {
    id: 'brdevs',
    title: 'BR Devs',
    company: 'Community Project',
    description:
      'Plataforma desenvolvida para comunidade de desenvolvedores brasileiros, com recursos de networking, compartilhamento de conhecimento e eventos.',
    technologies: ['React', 'TypeScript', 'Next.js', 'Vercel'],
    domain: 'Community',
    period: '2023',
    highlights: [
      'Plataforma comunitária',
      'Networking e eventos',
      'Deploy na Vercel',
    ],
    webUrl: 'https://brdevs.vercel.app/',
  },
  {
    id: 'sistema-feline',
    title: 'Sistema Feline',
    company: 'Freelance',
    description:
      'Sistema web desenvolvido para gestão e controle, com interface administrativa completa e funcionalidades de gerenciamento de dados.',
    technologies: ['React', 'TypeScript', 'Next.js', 'Backend Integration'],
    domain: 'Web Development',
    period: '2023',
    highlights: [
      'Sistema de gestão',
      'Interface administrativa',
      'Integração backend',
    ],
    webUrl: 'https://www.sistema-feline.com.br/',
  },
  // 2023 - 2024
  {
    id: 'iklaim',
    title: 'iKlaim',
    company: 'iKlaim',
    description:
      'Plataforma web desenvolvida para reclamações de voos e indenizações aéreas, permitindo que passageiros reivindiquem seus direitos de forma simples e eficiente. Desenvolvi a aplicação completa usando Next.js com internacionalização (i18n) para suportar múltiplos mercados (Brasil, Espanha, França, Estados Unidos), implementando backend em Node.js para processamento de reclamações, gestão de casos e integração com sistemas legais. A plataforma oferece interface intuitiva para registro de voos cancelados, atrasados, overbooking e problemas com bagagem, com acompanhamento em tempo real do status das indenizações.',
    technologies: [
      'Next.js',
      'TypeScript',
      'React',
      'Node.js',
      'i18n',
      'Internationalization',
      'Backend API',
      'Case Management',
    ],
    domain: 'Legal Tech',
    period: '2023 - 2024',
    highlights: [
      'Plataforma multilíngue para múltiplos mercados',
      'Sistema completo de gestão de reclamações',
      'Backend Node.js para processamento de casos',
      'Interface otimizada para conversão',
      'Acompanhamento em tempo real de indenizações',
    ],
    webUrl: 'https://iklaim.com/br',
  },
  // 2022 - 2023
  {
    id: 'maistodos',
    title: 'MaisTODOS (Cartão de Todos)',
    company: 'Cartão de Todos',
    description:
      'Trabalhei em um dos maiores apps nacionais do Brasil, usado por milhões de usuários, oferecendo uma extensa suíte de serviços incluindo agendamento médico, benefícios de saúde, cashback, carteira digital, escaneamento de código de barras para recibos fiscais, serviços baseados em geolocalização, gestão de saldo e transferências internas. Além da entrega de features, desempenhei papel crítico liderando e evangelizando engenharia de acessibilidade em toda a organização. Conduzi workshops de acessibilidade, apoiei UX Research, orientei Product em padrões de UX inclusivos, colaborei com design para redefinir comportamentos visuais, e ajudei squads de engenharia a adotar padrões baseados em WCAG como parte de sua cultura de desenvolvimento. Fui diretamente envolvida no planejamento e modelagem da versão V4 do app, redesenhando a UI para ser mais moderna, acessível e visualmente consistente, enquanto também implementava melhorias significativas de segurança em parceria com o backend, como padrões de criptografia, ofuscação de código e fluxos mais seguros de autenticação/autorização. O trabalho incluiu otimização de performance, refatoração de fluxos legados, e manutenção de comunicação robusta com backend, UX, QA e product teams.',
    technologies: [
      'React Native',
      'TypeScript',
      'GraphQL',
      'Accessibility',
      'Security',
      'Obfuscation',
      'Encryption',
      'Geolocation',
      'NFC/Camera',
      'OCR',
      'Digital Wallet',
      'Healthcare Integration',
    ],
    domain: 'Healthcare & Finance',
    period: '2022 - 2023',
    highlights: [
      'App usado por milhões de usuários no Brasil',
      'Liderança em cultura de acessibilidade organizacional',
      'Redesign V4 com segurança reforçada',
      'Workshops e evangelização a11y',
      'Melhorias de segurança em colaboração com backend',
      'Integração de múltiplos serviços (saúde, financeiro, geolocalização)',
    ],
    iosUrl: 'https://apps.apple.com/br/app/cart%C3%A3o-de-todos/id1536693230',
    androidUrl: 'https://play.google.com/store/apps/details?id=com.cartaodetodoswalletapp&hl=pt_BR',
  },
  // 2022
  {
    id: 'liberali',
    title: 'Agritech Offline-First Platform',
    company: 'Liberali',
    description:
      'Entreguei app React Native + Expo usado em grandes fazendas em Mato Grosso, onde conectividade de internet é extremamente limitada. O app permitiu trabalhadores registrar atividades diárias, uso de equipamentos, eventos de manutenção, conclusão de tarefas e rotinas operacionais totalmente offline, sincronizando dados uma vez que qualquer conexão estável fosse detectada. Projetei e implementei arquitetura offline-first centrada em SQLite, habilitando persistência local robusta, segurança transacional, sincronização baseada em fila, e estratégias de resolução de conflitos essenciais para fluxos de trabalho agrícolas do mundo real. O produto precisava funcionar em vastas áreas rurais, frequentemente sem 3G/4G, significando que o app tinha que armazenar dias de dados, gerenciar formulários complexos, e serializar logs de equipamentos de forma confiável.',
    technologies: [
      'React Native',
      'Expo',
      'SQLite',
      'Offline-First',
      'Conflict Resolution',
      'Background Sync',
      'Queue-based Sync',
      'Transactional Safety',
    ],
    domain: 'Agritech',
    period: '2022',
    highlights: [
      'Arquitetura offline-first com SQLite',
      'Sincronização em background com resolução de conflitos',
      'Funcionamento em ambientes de baixa conectividade',
      'Armazenamento de dias de dados offline',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.liberali.farm4all&hl=pt_BR',
    iosUrl: 'https://apps.apple.com/br/app/farm4all/id1527838572',
  },
  {
    id: 'hot-buttered-club',
    title: 'Hot Buttered Club',
    company: 'HB Club',
    description:
      'App de e-commerce desenvolvido para iOS e Android, oferecendo experiência de compra premium com interface moderna e funcionalidades avançadas de navegação e checkout.',
    technologies: ['React Native', 'TypeScript', 'iOS', 'Android', 'App Store', 'Play Store'],
    domain: 'E-commerce',
    period: '2022',
    highlights: [
      'App publicado na App Store e Play Store',
      'Interface moderna e intuitiva',
      'Experiência de compra otimizada',
    ],
    iosUrl: 'https://apps.apple.com/br/app/hot-buttered/id6738350135',
    androidUrl: 'https://play.google.com/store/apps/details?id=br.com.hb.v2',
  },
  {
    id: 'hb-rep',
    title: 'HB Rep',
    company: 'HB Club',
    description:
      'Aplicativo de representação comercial desenvolvido para facilitar o trabalho de representantes, com gestão de pedidos, catálogo de produtos e acompanhamento de vendas.',
    technologies: ['React Native', 'TypeScript', 'REST API', 'Play Store'],
    domain: 'E-commerce',
    period: '2022',
    highlights: [
      'App publicado na Play Store',
      'Gestão de representantes',
      'Catálogo e pedidos integrados',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=br.com.hb.representacao&hl=pt_BR',
  },
  {
    id: 'lojas-renner',
    title: 'Lojas Renner',
    company: 'Datum / Lojas Renner',
    description:
      'Contribuí para o lançamento do app de e-commerce multilíngue para o mercado uruguaio. Implementei acessibilidade, internacionalização, consistência cross-platform de UI, e fluxos de varejo de alta performance.',
    technologies: [
      'React Native',
      'TypeScript',
      'i18n',
      'Accessibility',
      'Play Store',
    ],
    domain: 'E-commerce',
    period: '2022',
    highlights: [
      'App multilíngue para mercado uruguaio',
      'Acessibilidade implementada',
      'Fluxos de alta performance',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.lojasrenner&hl=pt_BR',
    iosUrl: 'https://apps.apple.com/uy/app/renner/id6448287318',
  },
  // 2021 - 2022
  {
    id: 'osiris-agtech',
    title: 'Hydroponic Management App',
    company: 'Osíris Agtech',
    description:
      'Contribuí end-to-end para desenvolvimento de aplicativo híbrido mobile para gestão de cultivo hidropônico, usado por produtores agrícolas para monitorar, ajustar e otimizar soluções de nutrientes hidropônicos, ciclos de irrigação, equipamentos e rotinas diárias de cuidado com plantas. Meu trabalho abrangeu todo o ciclo de vida do produto: ajudei a projetar o protótipo, defini regras de negócio com pesquisadores de agritech, estruturei planejamento de sprints, construí layouts iniciais no Figma, e implementei toda a aplicação Flutter. Isso incluiu mapear fluxos de trabalho agrícolas reais, traduzir requisitos específicos de hidroponia em UI funcional, e moldar a arquitetura do app para suportar produtores com diferentes níveis de alfabetização técnica. Construí telas para medições de soluções, balanço de nutrientes, eventos de irrigação, inputs baseados em sensores, logs de crescimento de plantas e interações com equipamentos. Implementei cálculos de nutrientes, lógica de ciclos de irrigação, validação de dados de campo e transformação de regras de domínio. Também apoiei pipelines de deploy, publicando builds na Play Store e App Store, e integrando Firebase (autenticação, database, analytics) e APIs backend. Este projeto exigiu colaboração constante com agrônomos e equipe de pesquisa para garantir que o app correspondesse a práticas hidropônicas reais usadas no campo, incluindo testes em ambientes reais de cultivo.',
    technologies: [
      'Flutter',
      'Dart',
      'Figma',
      'Firebase',
      'REST API',
      'Play Store',
      'App Store',
      'Clean Architecture',
      'Domain-Driven Design',
      'Sensor Integration',
    ],
    domain: 'Agritech',
    period: '2021 - 2022',
    highlights: [
      'Desenvolvimento end-to-end completo (design a deploy)',
      'Protótipos e design no Figma',
      'Colaboração com agrônomos e pesquisadores',
      'Mapeamento de fluxos de trabalho agrícolas reais',
      'Deploy em Play Store e App Store',
      'Integração com sensores e equipamentos agrícolas',
      'Cálculos de nutrientes e ciclos de irrigação',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.osiris.osi_solucoes&hl=pt_BR',
    webUrl: 'https://osirisagtech.com.br/',
  },
  // 2021 - Presente
  {
    id: 'guria-shape',
    title: 'Guria Shape',
    company: 'Personal Project',
    description:
      'App fitness desenvolvido para ajudar usuárias a alcançarem seus objetivos de forma e saúde. App publicado na Play Store com funcionalidades de acompanhamento de treinos, nutrição e progresso.',
    technologies: ['React Native', 'TypeScript', 'Firebase', 'Play Store', 'App Store'],
    domain: 'Fitness',
    period: '2021 - Presente',
    highlights: [
      'App publicado na Play Store e App Store',
      'Acompanhamento de treinos e nutrição',
      'Interface intuitiva e acessível',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.gonzagajaque.guriashape&hl=pt_BR',
    iosUrl: 'https://apps.apple.com/br/app/guria-shape/id6466451203',
  },
  // 2021 (Mais Antigos)
  {
    id: 'trinus',
    title: 'Real Estate & Investment SuperApp',
    company: 'Trinus',
    description:
      'Melhorei plataforma mobile de grande escala de imóveis e investimentos com carteira digital, rastreamento de ativos, monitoramento de construção, e fluxos de documentos legais. Entreguei componentes de UI financeira estáveis, otimizei integrações backend, melhorei renderização de dados de alto volume, e mantive pipelines Azure DevOps CI/CD.',
    technologies: ['Flutter', 'Dart', 'Azure DevOps', 'REST API', 'Firebase'],
    domain: 'Real Estate & Finance',
    period: '2021',
    highlights: [
      'SuperApp de imóveis e investimentos',
      'Carteira digital e rastreamento de ativos',
      'CI/CD com Azure DevOps',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=app.facilita.trinusvendas&hl=pt_BR',
  },
  {
    id: 'app-fitness',
    title: 'App Fitness',
    company: 'AcessoWeb',
    description:
      'Aplicativo completo de fitness com funcionalidades de treinamento, acompanhamento de exercícios, e gestão de rotinas de treino. Desenvolvido com foco em usabilidade e performance.',
    technologies: ['React Native', 'TypeScript', 'REST API'],
    domain: 'Fitness',
    period: '2021',
    highlights: [
      'App publicado na Play Store',
      'Gestão completa de treinos',
      'Interface otimizada para performance',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.acessoweb.appfitness',
  },
  {
    id: 'barbearia-katana',
    title: 'Barbearia Katana',
    company: 'AcessoWeb',
    description:
      'App desenvolvido para barbearia com sistema de agendamento, gestão de clientes, e funcionalidades de fidelidade. Interface moderna e intuitiva para melhor experiência do usuário.',
    technologies: ['React Native', 'TypeScript', 'REST API', 'Play Store', 'App Store'],
    domain: 'Services',
    period: '2021',
    highlights: [
      'Sistema de agendamento',
      'Gestão de clientes',
      'App publicado na Play Store e App Store',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.acessoweb.barbeariakatana&hl=pt',
    iosUrl: 'https://apps.apple.com/fi/app/barbearia-katana/id6469011493',
  },
  {
    id: 'imoveis-livre',
    title: 'Imóveis Livre',
    company: 'AcessoWeb',
    description:
      'Aplicativo imobiliário com funcionalidades de busca, visualização de imóveis, agendamento de visitas e contato com corretores. Interface otimizada para facilitar a busca de propriedades.',
    technologies: ['React Native', 'TypeScript', 'REST API', 'Play Store', 'App Store'],
    domain: 'Real Estate',
    period: '2021',
    highlights: [
      'Busca avançada de imóveis',
      'Agendamento de visitas',
      'App publicado na Play Store e App Store',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.acessoweb.imoveislivre&hl=pt',
    iosUrl: 'https://apps.apple.com/py/app/im%C3%B3veis-livre/id6476892583',
  },
  {
    id: 'palavra-da-graca',
    title: 'Palavra da Graça',
    company: 'AcessoWeb',
    description:
      'App religioso desenvolvido para compartilhamento de conteúdo espiritual, com funcionalidades de leitura, áudio e vídeo. Interface acessível e otimizada para diferentes dispositivos.',
    technologies: ['React Native', 'TypeScript', 'Media Player', 'Play Store', 'App Store'],
    domain: 'Religion',
    period: '2021',
    highlights: [
      'Conteúdo multimídia',
      'Interface acessível',
      'App publicado na Play Store e App Store',
    ],
    androidUrl: 'https://play.google.com/store/apps/details?id=com.acessoweb.palavradagraca&hl=pt_BR',
    iosUrl: 'https://apps.apple.com/py/app/palavra-da-gra%C3%A7a/id6472688684',
  },
]

export const experiences: Experience[] = [
  {
    id: 'enor-securities',
    company: 'Enor Securities',
    role: 'Senior Mobile Developer',
    period: '2023 - Presente',
    description:
      'Trabalho como Senior Mobile Developer em aplicação de criptomoedas e ativos digitais baseada em El Salvador, focada em onboarding seguro, operações de carteira, validação de identidade, e fluxos multilíngues para usuários internacionais. Mantenho e evoluo toda a arquitetura v2 com foco em segurança, confiabilidade e internacionalização.',
    technologies: [
      'React Native',
      'TypeScript',
      'Security',
      'Obfuscation',
      'JADX',
      'GitLab CI',
      'Multi-language',
    ],
    highlights: [
      'Arquitetura v2 com segurança reforçada',
      'Fluxos multilíngues (ES/PT/EN)',
      'Revisões estáticas de segurança',
    ],
    domain: 'Fintech',
  },
  {
    id: 'gympass-wellhub',
    company: 'Gympass / Wellhub',
    role: 'React Native Accessibility Engineering',
    period: '2023 - Maio 2025',
    description:
      'Transformei app multiregional usado por 20M+ usuários em produto WCAG-aligned. Entreguei correções de acessibilidade cross-platform, construí componentes a11y-first para Yoga DS (open-source) e Yoga Inner, resolvi inconsistências profundas de TalkBack/VoiceOver, e habilitei fluxos inclusivos em 11 países. Fortaleci a cultura de desenvolvimento através de orientação arquitetural, padrões reutilizáveis e validação a11y apoiada por CI.',
    technologies: [
      'React Native',
      'TypeScript',
      'WCAG 2.1',
      'TalkBack',
      'VoiceOver',
      'Yoga Design System',
      'CI/CD',
    ],
    highlights: [
      'App usado por 20M+ usuários em 11 países',
      'Componentes a11y-first para design system open-source',
      'Workshops e cultura de acessibilidade',
      'Validação a11y automatizada em CI',
    ],
    domain: 'Health & Wellness',
  },
  {
    id: 'maistodos',
    company: 'Cartão de Todos (MaisTODOS)',
    role: 'Mobile Developer & Accessibility Leader',
    period: '2022 - 2023',
    description:
      'Trabalhei em um dos maiores apps nacionais do Brasil, usado por milhões de usuários, oferecendo serviços extensos incluindo agendamento médico, benefícios de saúde, cashback, carteira digital, escaneamento de código de barras para recibos fiscais, serviços baseados em geolocalização, gestão de saldo e transferências internas. Além da entrega de features, desempenhei papel crítico liderando e evangelizando engenharia de acessibilidade em toda a organização. Conduzi workshops de acessibilidade, apoiei UX Research, orientei Product em padrões de UX inclusivos, colaborei com design para redefinir comportamentos visuais, e ajudei squads de engenharia a adotar padrões baseados em WCAG como parte de sua cultura de desenvolvimento. Fui diretamente envolvida no planejamento e modelagem da versão V4 do app, redesenhando a UI para ser mais moderna, acessível e visualmente consistente, enquanto também implementava melhorias significativas de segurança em parceria com o backend, como padrões de criptografia, ofuscação de código e fluxos mais seguros de autenticação/autorização.',
    technologies: [
      'React Native',
      'TypeScript',
      'GraphQL',
      'Accessibility',
      'Security',
      'Obfuscation',
      'Encryption',
      'Geolocation',
      'NFC/Camera',
      'OCR',
    ],
    highlights: [
      'App usado por milhões de usuários no Brasil',
      'Liderança em cultura de acessibilidade organizacional',
      'Redesign V4 com segurança reforçada',
      'Workshops e evangelização a11y',
      'Melhorias de segurança em colaboração com backend',
    ],
    domain: 'Healthcare & Finance',
  },
  {
    id: 'liberali',
    company: 'Liberali',
    role: 'Mobile Developer',
    period: '2022',
    description:
      'Entreguei app React Native + Expo usado em grandes fazendas em Mato Grosso, permitindo operadores registrar tarefas diárias, uso de equipamentos, e operações de campo totalmente offline. Construí arquitetura offline-first robusta usando SQLite, resolução de conflitos, pipelines de sincronização em background.',
    technologies: [
      'React Native',
      'Expo',
      'SQLite',
      'Offline-First',
      'Conflict Resolution',
      'Background Sync',
    ],
    highlights: [
      'Arquitetura offline-first com SQLite',
      'Sincronização em background',
      'Resolução de conflitos',
    ],
    domain: 'Agritech',
  },
  {
    id: 'osiris-agtech',
    company: 'Osíris Agtech',
    role: 'Mobile Developer (Flutter)',
    period: '2021 - 2022',
    description:
      'Co-projetei app de gestão de hidroponia end-to-end: protótipos, regras de negócio, planejamento de sprints, UI no Figma, desenvolvimento Flutter, integrações backend, e deploy nas stores. Construí features para monitoramento de nutrientes, ciclos de irrigação, inputs baseados em sensores, e rotinas diárias de cultivo.',
    technologies: ['Flutter', 'Dart', 'Figma', 'Firebase', 'REST API'],
    highlights: [
      'Desenvolvimento end-to-end',
      'Protótipos e design no Figma',
      'Colaboração com agrônomos',
    ],
    domain: 'Agritech',
  },
  {
    id: 'kmm-nstech',
    company: 'KMM by nstech',
    role: 'Mobile Developer',
    period: '2022',
    description:
      'Melhorei software crítico de logística que alimenta operações de caminhões, recebimento de armazéns, cadeias de suprimentos de cervejarias e fluxos de trabalho de frete industrial. Entreguei novas features em React Native, estabilizei lógica backend PL/SQL, corrigi bugs críticos de mobile impactando eventos reais de logística, e alinhei frontend/mobile/backend em múltiplos produtos usados diariamente por motoristas, operadores e grandes fabricantes de bebidas.',
    technologies: [
      'React Native',
      'TypeScript',
      'PL/SQL',
      'Backend Integration',
      'Logistics Domain',
    ],
    highlights: [
      'Software crítico de logística',
      'Múltiplos produtos integrados',
      'Correção de bugs críticos',
      'Alinhamento frontend/mobile/backend',
    ],
    domain: 'Logistics',
  },
  {
    id: 'datum-renner',
    company: 'Datum / Lojas Renner',
    role: 'Mobile Developer',
    period: '2022',
    description:
      'Contribuí para o lançamento de app de varejo multilíngue React Native para o mercado uruguaio. Implementei acessibilidade, internacionalização, consistência cross-platform de UI, e fluxos de varejo de alta performance. Melhorei mecânicas de troca de idioma, navegação, semântica de componentes, e confiabilidade de release através de Apple Store Connect e instrumentação Firebase.',
    technologies: [
      'React Native',
      'TypeScript',
      'i18n',
      'Accessibility',
      'Apple Store Connect',
      'Firebase',
    ],
    highlights: [
      'Lançamento de app multilíngue',
      'Mercado uruguaio',
      'Acessibilidade e internacionalização',
      'Fluxos de alta performance',
    ],
    domain: 'E-commerce',
  },
  {
    id: 'trinus',
    company: 'Trinus',
    role: 'Flutter Mobile Developer',
    period: '2021',
    description:
      'Melhorei plataforma mobile de grande escala de imóveis e investimentos com carteira digital, rastreamento de ativos, monitoramento de construção, e fluxos de documentos legais. O app serviu como hub unificado onde usuários podiam acessar extratos de investimento, gráficos de performance de ativos, documentação imobiliária, processos legais, cronogramas de construção, estágios de contratos e atualizações de propriedades, tudo com alta disponibilidade e padrão rigoroso de confiabilidade. Implementei novas features na carteira de investimento, melhorei fluxos transacionais, refatorei componentes de UI para melhor escalabilidade, e otimizei integração com serviços backend. Também mantive e melhorei pipelines Azure DevOps CI/CD, garantindo builds e deployments confiáveis para Android e iOS.',
    technologies: ['Flutter', 'Dart', 'Azure DevOps', 'REST API', 'Firebase'],
    highlights: [
      'SuperApp de imóveis e investimentos',
      'Carteira digital e rastreamento de ativos',
      'CI/CD com Azure DevOps',
      'Alta disponibilidade e confiabilidade',
    ],
    domain: 'Real Estate & Finance',
  },
]

export const skills: SkillCategory[] = [
  {
    id: 'mobile-engineering',
    name: 'Mobile Engineering',
    items: [
      'React Native',
      'Flutter',
      'iOS',
      'Android',
      'TypeScript',
      'JavaScript',
      'Modular Architecture',
      'DDD',
      'Performance Optimization',
    ],
  },
  {
    id: 'accessibility',
    name: 'Accessibility (A11y)',
    items: [
      'WCAG 2.1',
      'Semantic Navigation',
      'TalkBack',
      'VoiceOver',
      'Focus Management',
      'Screen Reader Testing',
      'A11y-first Components',
    ],
  },
  {
    id: 'state-management',
    name: 'State Management',
    items: ['Redux', 'Zustand', 'Context API', 'GraphQL (Apollo)', 'REST', 'WebSocket'],
  },
  {
    id: 'testing',
    name: 'Testing & Quality',
    items: [
      'Jest',
      'React Native Testing Library',
      'Maestro E2E',
      'Detox',
      'Snapshot Testing',
      'A11y Testing',
    ],
  },
  {
    id: 'cicd',
    name: 'CI/CD & Release',
    items: [
      'GitHub Actions',
      'GitLab CI',
      'Fastlane',
      'CodePush',
      'App Store',
      'Play Store',
      'Azure DevOps',
    ],
  },
  {
    id: 'security',
    name: 'Security & Observability',
    items: [
      'Secure Storage',
      'Obfuscation',
      'Encryption',
      'OAuth/JWT',
      'Sentry',
      'Firebase Analytics',
      'Performance Profiling',
    ],
  },
  {
    id: 'offline',
    name: 'Offline-First & Data',
    items: [
      'SQLite',
      'MMKV',
      'Realm',
      'Background Sync',
      'Conflict Resolution',
      'Queue-based Updates',
    ],
  },
  {
    id: 'tools',
    name: 'Dev Tools',
    items: [
      'Git',
      'GitHub',
      'GitLab',
      'Flipper',
      'Reactotron',
      'Figma',
      'Node.js',
      'Docker',
    ],
  },
]
